package com.jobportal.daoimpl;
import com.jobportal.dao.JobSeekerDao;
import com.jobportal.db.DBConnection;
import com.jobportal.dto.JobSeeker;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class JobSeekerDaoImpl implements JobSeekerDao {

    private Connection con;

    public JobSeekerDaoImpl() {
        con = DBConnection.getConnection();
    }

    // 1️⃣ Create job seeker profile
    @Override
    public boolean createJobSeeker(JobSeeker js) {

        String sql = """
            INSERT INTO job_seekers
            (user_id, full_name, phone, total_experience, profile_completion)
            VALUES (?, ?, ?, ?, ?)
        """;

        try (PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, js.getUserId());
            ps.setString(2, js.getFullName());
            ps.setString(3, js.getPhone());
            ps.setInt(4, js.getTotalExperience());
            ps.setInt(5, js.getProfileCompletion());

            return ps.executeUpdate() > 0;

        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    // 2️⃣ Get job seeker by user ID
    @Override
    public JobSeeker getJobSeekerByUserId(int userId) {

        String sql = "SELECT * FROM job_seekers WHERE user_id = ?";

        try (PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, userId);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                return mapJobSeeker(rs);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    // 3️⃣ Get job seeker by ID
    @Override
    public JobSeeker getJobSeekerById(int jobSeekerId) {

        String sql = "SELECT * FROM job_seekers WHERE id = ?";

        try (PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, jobSeekerId);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                return mapJobSeeker(rs);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    // 4️⃣ Update job seeker profile
    @Override
    public boolean updateJobSeeker(JobSeeker js) {

        String sql = """
            UPDATE job_seekers
            SET full_name = ?, phone = ?
            WHERE id = ?
        """;

        try (PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, js.getFullName());
            ps.setString(2, js.getPhone());
            ps.setInt(3, js.getId());

            return ps.executeUpdate() > 0;

        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    // 5️⃣ Update profile completion %
    @Override
    public boolean updateProfileCompletion(int jobSeekerId, int profileCompletion) {

        String sql = "UPDATE job_seekers SET profile_completion = ? WHERE id = ?";

        try (PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, profileCompletion);
            ps.setInt(2, jobSeekerId);

            return ps.executeUpdate() > 0;

        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    // 6️⃣ Update total experience (calculated from Experience table)
    @Override
    public boolean updateTotalExperience(int jobSeekerId, int totalExperience) {

        String sql = "UPDATE job_seekers SET total_experience = ? WHERE id = ?";

        try (PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, totalExperience);
            ps.setInt(2, jobSeekerId);

            return ps.executeUpdate() > 0;

        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }
 // Inside com.jobportal.daoimpl.JobSeekerDaoImpl.java
    public int registerJobSeeker(JobSeeker seeker) {
    	
        String sql = "INSERT INTO job_seekers (name, email) VALUES (?, ?)";
        
        // 1. Use RETURN_GENERATED_KEYS to ask MySQL for the new ID
        try (Connection con = DBConnection.getConnection();
             PreparedStatement ps = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            
            ps.setString(1, seeker.getFullName());
            ps.setString(2, seeker.getEmail());
            
            int affectedRows = ps.executeUpdate();

            if (affectedRows > 0) {
                // 2. Retrieve the actual ID generated by MySQL
                try (ResultSet rs = ps.getGeneratedKeys()) {
                    if (rs.next()) {
                        return rs.getInt(1); // This returns the real ID (e.g., 25)
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return -1; 
    }

    // 🔁 Common mapper
    private JobSeeker mapJobSeeker(ResultSet rs) throws Exception {

        JobSeeker js = new JobSeeker();
        js.setId(rs.getInt("id"));
        js.setUserId(rs.getInt("user_id"));
        js.setFullName(rs.getString("full_name"));
        js.setPhone(rs.getString("phone"));
        js.setTotalExperience(rs.getInt("total_experience"));
        js.setProfileCompletion(rs.getInt("profile_completion"));
        return js;
    }
}